### ISSUE TITLE
Document version

### ISSUE THREAD

**Issue by marcospassos** [zentity-io/zentity#33]
How can I include the `_version` in the resolution result?

**Comment by davemoore-** [comment]
@marcospassos 

This should be easy for me to add. I can see this feature being useful for other users, too.

Currently there is no option in zentity to return the `"_version"` field of a document. What I can do is add an optional URL parameter in the [Resolution API](https://zentity.io/docs/rest-apis/resolution-api/) that instructs zentity to add [`"version": true`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html#search-search-api-query-params) to the query objects that it submits to Elasticsearch, and then include the `"_version"` field of each document in the response. I'd like to keep it optional simply because it's optional in Elasticsearch, and it would be good to match the experience of Elasticsearch as closely as possible.

**Comment by davemoore-** [comment]
I've released [zentity-1.5.2](https://zentity.io/releases/#zentity-1.5.2) which introduces a `_version` URL parameter to the [Resolution API](https://zentity.io/docs/rest-apis/resolution-api/). When submitting a resolution request with `_version=true` in the URL, the result will include the `"_version"` field in each document.
