### ISSUE TITLE
maxClauseCount exception thrown for a simple model

### ISSUE THREAD

**Issue by erewok** [zentity-io/zentity#36]
I [commented on the Elasticsearch discourse](https://discuss.elastic.co/t/zentity-resolution-leads-to-maxclausecount-queries/221463) about an issue I am having where a simple model with a resolver for name and phone leads to an exception due to a large clause and someone recommended I post it over here.

The exception looks like this:

```
org.elasticsearch.ElasticsearchException$1: maxClauseCount is set to 1024
	at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:639) ~[elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:137) [elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:264) [elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.search.InitialSearchPhase.onShardFailure(InitialSearchPhase.java:105) [elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.search.InitialSearchPhase.access$200(InitialSearchPhase.java:50) [elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.search.InitialSearchPhase$2.onFailure(InitialSearchPhase.java:273) [elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-7.3.2.jar:7.3.2]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.3.2.jar:7.3.2]
```

This is on an index with about 13 million entries, and a model with a single resolver that looks at name and phone number. Iterating through a test set of amounting to 1000 records total where each record has a name and phone number, I get the above exceptions thrown periodically.

What's worse, anytime these errors are thrown, it takes around 10-30 seconds to resolve itself, which makes it too slow for processing the full data set (around 70k entries).

Just before the exception, the console dumps part of the query to stderr and it looks like a giant query with all of the different phone numbers in the index.

Is there something I can do to prevent this from happening? Is this a result of something I have configured incorrectly?

**Comment by davemoore-** [comment]
@erewok

Most likely what you're seeing is "snowballing." This happens when the matchers or resolvers are too liberal, causing too many false matches to "snowball" into the result. When there are many false matches, the number of searchable attribute values explodes and the queries become too complex for Elasticsearch to process.

For example, let's say you have a resolver that looks at names and phone numbers, and let's say your data has a thousand documents where the value of the name is `"unknown"` or `""`. If your search matches one of those values, then suddenly your resolution job might incorrectly pick up a thousand phone numbers associated with the name `"unknown"` or `""`. Then each newly discovered phone number is included as a clause in the next query, which could exceed what Elasticsearch can process.

My recommendations would be:

- Check for common values in your data that might cause snowballing, such as a name whose value is `"unknown"`, and exclude those values from any searches by setting them in [`"scope"."exclude"."attributes"`](https://zentity.io/docs/entity-resolution/input-specification/#scope.exclude.attributes.ATTRIBUTE_NAME).
- Check to see if your matchers are too liberal. For example, if the names and phone numbers are [text](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html) fields instead of [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html) fields, and if your matchers are using a [`"match"`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query.html) query instead of a [`"term"`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) query, then check the [analyzers](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html) for those text fields. It's possible that the queries are matching tokens instead of the full values, such as just the first names or area codes of the phone numbers, and that could lead to more false matches and snowballing. For example, the name "Jane Smith" and the phone number "555-123-4567" could be matching even if the input values are "Jane" and "555," which is too generous of a match. If this is happening, consider reindexing your data using a custom text [analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/configure-text-analysis.html) or keyword [normalizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/normalizer.html) that doesn't tokenize the value.

Some of this is covered in the [entity modeling tips](https://zentity.io/docs/entity-models/tips/) section of the documentation.

**Comment by erewok** [comment]
I think you're right, actually. While I was surprised to see the exception thrown, it turned to be from inputs that were either empty strings or really common matching patterns. I will read the documentation you have linked here. Thanks for the response!
