### ISSUE TITLE
Support for ES 7.7.1 or 7.8

### ISSUE THREAD

**Issue by seanlindo** [zentity-io/zentity#47]
We discovered while planning a cluster upgrade that we'd have to remove Zentity functionality completely because the plugin does not register itself as being compatible. Are there any plans to address this?

**Comment by austince** [comment]
We're just starting to use zentity as well, maybe we could make a contribution. Do you know what is needs to be updated?

**Comment by davemoore-** [comment]
@seanlindo I've released [zentity-1.6.1](https://zentity.io/releases/#zentity-1.6.1) which supports Elasticsearch 7.7.0 through the latest 7.10.1.

I may write a guide to help people perform compatibility updates in the event that I can't update the plugin quickly enough for current releases of Elasticsearch. I'll always be slightly behind from the latest version of Elasticsearch, because I can only be reactive to those releases. Sometimes I'm quick about it, but the longer waits happen when there are breaking changes in the Elasticsearch Java API (as there were in 7.7.0).
