### ISSUE TITLE
Not matching

### ISSUE THREAD

**Issue by mmuruganandam** [zentity-io/zentity#7]
I am using elastic 6.2.4 and the zentity plugin 6.2.4 (Version 1.0.0).

**URL:** /_zentity/models/test

My model is:
`{
  "attributes": {
    "name": {
      "type": "string"
    },
    "ssn": {
      "type": "string"
    }
  },
  "resolvers": {
    "name_ssn": {
      "attributes": [
        "name", "ssn"
      ]
    },
    "name_only": {
      "attributes": [
        "name"
      ]
    }
  },
  "matchers": {
    "exact": {
      "clause": {
        "term": {
          "{{ field }}": "{{ value }}"
        }
      }
    },
    "fuzzy": {
      "clause": {
        "match": {
          "{{ field }}": {
            "query": "{{ value }}",
            "fuzziness": 2
          }
        }
      }
    }
  },
  "indices": {
    "test": {
      "fields": {
        "FIRST_NAME": {
          "attribute": "name",
          "matcher": "fuzzy"
        },
        "LAST_NAME": {
          "attribute": "name",
          "matcher": "fuzzy"
        },
        "SSN": {
          "attribute": "ssn",
          "matcher": "exact"
        }
      }
    }
  }
}`

**URL:** /_zentity/resolution/test

My resolution is:
`{
  "attributes": {
    "name": [ "Muruga Mani" ],
    "ssn": [
        "111-22-3333"
      ]
  },
  "include": {
    "indices": ["test"],
    "resolvers": ["name_only"]
  }
}`

or 

`{
  "attributes": {
    "name": [ "Muruga Mani" ],
    "ssn": [
        "111-22-3333"
      ]
  }
}`

My data in ES is (in index test and type person):
`{"LAST_NAME":"Mani","FIRST_NAME":"Muruga","SSN":"111-22-3333"}`

But it is not resolving the match.

My response is:
`{"took":8,"hits":{"total":0,"hits":[]}}`

What am I missing here?

**Comment by davemoore-** [comment]
@mmuruganandam

The `"include"` field in your resolution request needs to be nested under a `"scope"` field.

Example:

```javascript
POST _zentity/resolution/test
{
  "attributes": {
    "name": ["Muruga Mani"],
    "ssn": ["111-22-3333"]
  },
  "scope": {
    "include": {
      "indices": ["test"],
      "resolvers": ["name_only"]
    }
  }
}
```

I tested this with your data and it resolved the issue.

Source: https://zentity.io/docs/entity-resolution/input-specification/#scope

Ideally, whenever there's an unrecognized field in the request, an error should be raised to prevent any confusion for the client. So I'll treat this as a bug and submit a separate issue to resolve it.

**Comment by mmuruganandam** [comment]
@davemoore- thank you!  I could make this work with the scope now for **name_only** resolver.  I am not sure what could be the issue when I use the **name_ssn** resolver as it doesn't return any response.  Even though the inputs are matching, it is not returning any values.

**Comment by davemoore-** [comment]
@mmuruganandam 

I suspect you might be trying to perform a [`term`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) query on a [`text`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) field instead of a [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html) field. Elasticsearch [terms queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) were designed to operate on exact keyword fields.

By chance did you define the mapping for your test index, or did Elasticsearch create it dynamically?

Elasticsearch will create the mapping for an index dynamically if the index doesn't exist. When it does this, by default it will index any string value in two ways: once as a `text` field and once as a `keyword` field.

We can see how that works. Let's start from scratch:

```javascript
DELETE test
```

Now let's add a document:

```javascript
PUT test/doc/1
{
  "LAST_NAME": "Mani",
  "FIRST_NAME": "Muruga",
  "SSN": "111-22-3333"
}
```

Now let's see how Elasticsearch created the index mapping:

```javascript
GET test/_mapping
```

It should look like this:

```javascript
{
  "test": {
    "mappings": {
      "doc": {
        "properties": {
          "FIRST_NAME": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "LAST_NAME": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "SSN": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    }
  }
}
```

Note the `"keyword"` field under `"SSN"`. If this is what you see in your mapping, then you'll want to change `"SSN"` to `"SSN.keyword"` in your entity model.

Here's what your `"indices"` field should look like in that case:

```javascript
{
 ...
  "indices": {
    "test": {
      "fields": {
        "FIRST_NAME": {
          "attribute": "name",
          "matcher": "fuzzy"
        },
        "LAST_NAME": {
          "attribute": "name",
          "matcher": "fuzzy"
        },
        "SSN.keyword": {
          "attribute": "ssn",
          "matcher": "exact"
        }
      }
    }
  }
}
```

Once I made this change using your data, I was able to match your document using your `"name_ssn"` resolver.

**Comment by mmuruganandam** [comment]
Thank you @davemoore-  for the help, I could now able to match.  Thanks again!
